### ISSUE TITLE
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int32 of argument 'x'

### ISSUE THREAD

**Issue by MuruganR96** [JanhHyun/Speaker_Verification#16]
i was passes embeddings (enrollment, verification) checked similarities between these.
throws this issue.  
```
Traceback (most recent call last):
   File "just_see.py", line 178, in speaker_verification
    similarity_matrix = similarity(embedded=verif_embed, w=1, b=0, N=N, M=M, P=proj, center=enroll_embed)
  File "just_see.py", line 105, in similarity
    S = tf.abs(w)*S+b   # rescaling
  File "/env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 866, in binary_op_wrapper
    return func(x, y, name=name)
  File "/env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul
    "Mul", x=x, y=y, name=name)
  File "/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int32 of argument 'x'.
```

**Comment by 00001101-xt** [comment]
@MuruganR96 

Try `w=1.0, b=1.0` should resolve the problem.

**Comment by MuruganR96** [comment]
@xtluo-ai  sir Thanks. it is my mistake.resolved
