### ISSUE TITLE
Failed to interpret file '.../p254_237.wav' as a pickle

### ISSUE THREAD

**Issue by arjmandi** [JanhHyun/Speaker_Verification#20]
Hi, 
I'm trying to run the code on using the VCTK dataset but get this error in the train function of `model.py`. Any ideas?
In other words, why are you reading sample files in training with npyio.load function? isn't this function designed to read/write numpy arrays from/to disk?

```Traceback (most recent call last):
  File "/home/mohsen/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: bad pickle data
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/mohsen/.IntelliJIdea2018.3/config/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/mohsen/.IntelliJIdea2018.3/config/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mohsen/workspace/Speaker_Verification/main.py", line 14, in <module>
    train(config.model_path)
  File "/home/mohsen/workspace/Speaker_Verification/model.py", line 69, in train
    _, loss_cur, summary = sess.run([train_op, loss, merged], feed_dict={batch: random_batch(utter_start=1), lr: config.lr * lr_factor})
  File "/home/mohsen/workspace/Speaker_Verification/utils.py", line 78, in random_batch
    utters = np.load(os.path.join(path, file))        # load utterance spectrogram of selected speaker
  File "/home/mohsen/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/home/mohsen/workspace/Speaker_Verification/train_tisv/p254_237.wav' as a pickle```

**Comment by arjmandi** [comment]
In other words, why are you reading sample files in training with `npyio.load` function? isn't this function designed to read/write numpy arrays from/to disk?

**Comment by ysaidcan** [comment]
How could you solve this issue? I am having the same error. I think it is caused by numpy version but still could not figure it out.
